### ISSUE TITLE
Family Road Map

### ISSUE THREAD

**Issue by axrez** [SOSChildrensVillages/HackXmas2019#13]
Issues of the current implementation (in order of complexity):
1. The illustration is linear and the goal is necessarily not
2. The current goal measurement does not reflect progress, but status
3. It is hard to decide what a sub goal means in term of progress
4. Do different cultures respond equally to the same icons?

Let’s assume we have the right icons based on the target audience:

We came up with the following suggested solutions with associated pros and cons:
* Show progress as a linear progression of time:
       * Easy to communicate and understand
       * Easy to visualise
       * Requires some work on the caretakers part to explain what should have been accomplished in the passed time and if it has been.
 * Show progress over a set of sub goals
       * Hard to define subgoals
       * Hard to communicate progression in a sensible way
* Trello board with icons and/or pictures
       * Allow for an easy physical replication, which can lead to a sense of accomplishment and work as a reward
       * Easy to manage in the app 
       * Requires some sort of icons to communicate to the illiterate 
       * Might become to abstract of a concept
       * Easy to illustrate with pictures
       * Allows the social worker to hand over a physical artifact as a symbol of progression
       * Receives a black white picture of current goal which get changed out for a colored picture once the goal is completed

[Prettier Google Docs link](https://docs.google.com/document/d/1-Za6LU7yL8GoPZbrJqF-fTb4AkHLIkXBVX_DyrHUrI4/edit?usp=sharing)

**Comment by strabu** [comment]
Thanks for your inputs :)
